
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import Header from "@/components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "shop",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
   <body className={`${inter.className} h-[100vh] w-[100vw]`}>
            <StoreProvider>
               <Header>
                  {children}
               </Header>
            </StoreProvider>
         </body>
      </html>
   );
}
